name: CICD-SSH
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
            set -e
            echo "Starting deployment process..."
            whoami
            ls -al
            echo "Changing to git directory..."
            cd git || { echo "Failed to change to git directory"; exit 1; }
            echo "Current directory:"
            pwd
            echo "Contents of git directory:"
            ls -al
            echo "Changing to repository directory..."
            cd ${{ github.event.repository.name }} || { echo "Failed to change to repository directory"; exit 1; }
            echo "Current directory:"
            pwd
            echo "Contents of repository directory:"
            ls -al
            if [ -f "deploy.sh" ]; then
              echo "Running deploy script..."
              chmod +x deploy.sh
              ./deploy.sh
            else
              echo "deploy.sh not found. Skipping deployment."
              exit 1
            fi
            echo "Deployment completed successfully."