name: CICD-SSH
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ github.event.repository.name }}
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
            set -e
            echo "Starting deployment process..."
            whoami
            ls -al
            echo "Changing to git directory..."
            cd git || exit 1
            echo "Changing to repository directory..."
            cd $REPO_NAME || exit 1
            echo "Running deploy script..."
            chmod +x deploy.sh
            sh deploy.sh
            echo "Deployment completed successfully."